### ISSUE TITLE
Initial pose of the human and plan to a target

### ISSUE THREAD

**Issue by CamilleMaurice** [baxter-flowers/human_moveit_config#3]
Dear buschbapti
I know this is not a release version. But I'd like to generate trajectories such as the hand of the human starts from an initial pose and reach a target object. According to a comment from last year:
"The basic concept is having a human model that you can move (FK and IK) and this does not require much of dependencies. Try the demo.launch to see if you can already start this. "
I tried to launch demo.launch

and I encounter the following Error message 
[FATAL] [1525705009.140918707]: Parameter '~moveit_controller_manager' not specified. This is needed to identify the plugin to use for interacting with controllers. No paths can be executed.

then: 
[ INFO] [1525705016.825606008]: TrajectoryExecution will use old service capability.
[ INFO] [1525705016.825651570]: Ready to take MoveGroup commands for group UpperBody.
[ INFO] [1525705017.025076220]: TrajectoryExecution will use old service capability.
[ INFO] [1525705017.025123595]: Ready to take MoveGroup commands for group LowerBody.
[ INFO] [1525705017.427605734]: TrajectoryExecution will use old service capability.
[ INFO] [1525705017.427652299]: Ready to take MoveGroup commands for group WholeBody.
[ WARN] [1525705018.463837821]: Joint values for monitored state are requested but the full state is not known
Ready to compute IK

Then I do not know how I can set a target location for the right hand (for exemple) and plan the trajectory. Is it easy to do ? Could you give me some hints ?
Thanks you very much
Camille M

**Comment by ymollard** [comment]
I haven't been using that package for a while so can't remember precisely, but as far as I can see, I guess there's not need for any controller manager since there's no robot to control. You can either:

- set `fake_execution:=true` to `move_group.launch`, which will load the fake controller, and make sure MoveIt still works as you expect
- generate a brand new empty MoveIt configuration with `setup_assistant.launch` that will create new launch files suitable for new MoveIt versions

Although it says it is fatal, it looks like it does not prevent the rest of MoveIt from starting though. If you can see the MoveIt GUI, you can move the handle of the right hand and then click on the "Planning" tab like within [this screenshot](https://answers.ros.org/upfiles/1409818506870462.png) to plan ad visualize the trajectory. For other uses of MoveIt you should read the [howto](http://docs.ros.org/kinetic/api/moveit_tutorials/html/index.html).

**Comment by buschbapti** [comment]
Dear Camille,

I have had troubles to run the package with newer versions of ROS (it was developped with Indigo). I believe new changes in Moveit might cause some issues. I haven't digged into it yet. If I understand correctly your needs you want to use Moveit to generate a path for the human hand. This is something we haven't tried as we were just using the basics IK and FK to follow trajectories we had defined separately. Even if you manage to make it work I am not sure this package will suits your need. The human model is defined as 5 independent kinematic chains starting from the pelvis. Therefore Moveit will only act on the joints of the chain that includes the end-effector you try to control. The rest of the body will stay still which means you loose a lot of DOF. We have designed it this way as Moveit could not handle tree structured URDF. It might be the case now but I am not sure. Thus I would recommand you to either make a URDF model as a tree with multiple end effectors if Moveit now supports it or use an homemade IK function that acts on all the joints and not rely on Moveit path planning capacities. The later is the approach we have considered.

**Comment by CamilleMaurice** [comment]
@ymollard  Thank you for your answer. I can now launch the demo with your indications. I also regenerated a package with the MoveIt! Setup Assistant and the present urdf. 
@buschbapti Thank you very much, I installed ROS Indigo to get more chances to get everything running. I'll take into consideration your comment.
